# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Liam0x80

# Build settings
markdown: CommonMarkGhPages
highlighter: rouge


# url
tag_dir: tag/

# Produces a cleaner folder structure when using categories
permalink: /:year/:month/:title.html

commonmark:
  options: ["SMART", "FOOTNOTES"]
  extensions: ["strikethrough", "autolink", "table", "tagfilter"]